# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
warnings_are_errors: true
sudo: required

cache: packages
before_install:
  - sudo apt-get -y install libharfbuzz-dev
  - sudo apt-get -y install libfribidi-dev
addons:
  apt:
    update: true

matrix:
  include:
   - r: release
   - r: devel


before_cache: Rscript -e 'remotes::install_cran("textshaping");remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github(ssh_id = Sys.getenv("TRAVIS_DEPLOY_KEY", ""))'
  skip_cleanup: true
